env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  jest: true
extends: 
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: latest
rules: {}
overrides: 
  - files:
      - "**/*.test.js"
      - "**/*.spec.js"
    env:
      jest: true